# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AnnotationTool
                                 A QGIS plugin
 Plugin for annotation work. Kind of Similar to CVAT
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-20
        copyright            : (C) 2026 by Shagun Rana
        email                : shagunkharwal@outlook.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AnnotationTool class from file AnnotationTool.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Anno_tool import AnnotationTool
    return AnnotationTool(iface)
